title: testing-generation
tagline: A brand new course on Learning Lab
description: I am testing the course generator
template:
  repo: testing-generation-template
  name: testing-generation
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: gate
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
